//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_log
    {
        public int tid { get; set; }
        public string name { get; set; }
        public byte transaction_type { get; set; }
        public string destination { get; set; }
        public long amount { get; set; }
        public long balance { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
